version: "3.4"
services:
    redis:
        image: redis:7-alpine
        volumes:
            - redis_data:/data
        restart: always

    web:
        build:
            context: .
            dockerfile: Dockerfile.django
            args:
                PIPENV_ARGS:
        ports:
            - "${APP_PORT:-8087}:8080"
        volumes:
            - .:/app
        restart: unless-stopped # unless-stopped on-failure

    quasar:
        tty: true
        build:
            context: .
            dockerfile: Dockerfile.quasar
#          target: 'production-stage'
        ports:
            - '${NGINX_PORT:-8088}:80'
        volumes:
            - '.:/app'
            - './nginx.conf:/etc/nginx/nginx.conf'
            - './logs:/var/log/nginx/server'
        links:
            - "web:web"
        healthcheck:
            test: "curl -m 5 http://localhost"
            interval: 5s
            timeout: 10s
            start_period: 10s
            retries: 3

    huey:
        build:
            context: .
            dockerfile: Dockerfile.django
        restart: unless-stopped
        volumes:
            - ./:/app
        entrypoint: ["python3", "manage.py", "run_huey"]

volumes:
    redis_data:
