# Generated by Django 4.2.5 on 2023-09-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_productpricehistory_created_and_more"),
        ("parser", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parsetask",
            options={
                "verbose_name": "Задача парсера",
                "verbose_name_plural": "Задачи парсера",
            },
        ),
        migrations.AddField(
            model_name="parsetask",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AddField(
            model_name="parsetask",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Дата редактирования"
            ),
        ),
        migrations.AlterField(
            model_name="parsetask",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="products.product"
            ),
        ),
        migrations.AlterField(
            model_name="parsetask",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Создана"),
                    (2, "В работе"),
                    (3, "Отменена"),
                    (4, "Пауза"),
                    (5, "Остановлена"),
                ],
                default=1,
                verbose_name="Статус",
            ),
        ),
    ]
