# Generated by Django 4.2.5 on 2023-09-05 07:41

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0002_alter_parsetask_options_parsetask_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parsetask",
            name="period",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    (1, "Ежедневно"),
                    (2, "Дважды в месяц"),
                    (3, "Раз в месяц"),
                    (4, "Ежеквартально"),
                    (5, "Единоразово"),
                ],
                default=1,
                max_length=20,
                verbose_name="Периодичность мониторинга",
            ),
        ),
        migrations.AddField(
            model_name="parsetask",
            name="period_date1",
            field=models.DateField(blank=True, null=True, verbose_name="Дата 1"),
        ),
        migrations.AddField(
            model_name="parsetask",
            name="period_date2",
            field=models.DateField(blank=True, null=True, verbose_name="Дата 2"),
        ),
        migrations.AlterField(
            model_name="parsetask",
            name="notifications_target",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("decr", "Цена конкурента уменьшилась"),
                    ("incr", "Цена конкурента увеличилась"),
                ],
                max_length=20,
                null=True,
                verbose_name="Цель уведомления",
            ),
        ),
        migrations.AlterField(
            model_name="parsetask",
            name="urls",
            field=models.TextField(null=True, verbose_name="URL сайтов"),
        ),
    ]
