# Generated by Django 4.2.5 on 2023-09-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0003_parsetask_period_parsetask_period_date1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteParseSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(verbose_name="Адрес страницы")),
                ("path_title", models.TextField(verbose_name="Путь к названию товара")),
                ("path_price", models.TextField(verbose_name="Путь к цене товара")),
            ],
            options={
                "verbose_name": "Настройки парсинга сайта",
                "verbose_name_plural": "Настройки парсинга сайта",
            },
        ),
    ]
