# Generated by Django 4.2.5 on 2023-09-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser", "0004_siteparsesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteparsesettings",
            name="parse_mode",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "HTML"), (2, "JSON")],
                default=1,
                verbose_name="Режим парсинга",
            ),
        ),
        migrations.AddField(
            model_name="siteparsesettings",
            name="request_data",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Данные запроса"
            ),
        ),
        migrations.AddField(
            model_name="siteparsesettings",
            name="request_headers",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Заголовки запроса"
            ),
        ),
    ]
