# Generated by Django 4.2.5 on 2023-09-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser", "0006_siteparsesettings_request_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteparsesettings",
            name="url",
            field=models.URLField(max_length=500, verbose_name="Адрес страницы"),
        ),
    ]
