# Generated by Django 4.2.5 on 2023-09-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser", "0007_alter_siteparsesettings_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteparsesettings",
            name="domain",
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
