# Generated by Django 4.2.5 on 2023-09-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser", "0008_siteparsesettings_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteparsesettings",
            name="url_match",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Адрес страницы задачи",
            ),
        ),
        migrations.AlterField(
            model_name="siteparsesettings",
            name="url",
            field=models.URLField(max_length=500, verbose_name="Адрес страницы запроса"),
        ),
    ]
