# Generated by Django 4.2.5 on 2023-09-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser", "0009_siteparsesettings_url_match_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteparsesettings",
            name="force_parser_url",
            field=models.BooleanField(default=False, verbose_name="Принудительно использовать URL парсера"),
        ),
    ]
