# Generated by Django 4.2.5 on 2023-09-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser", "0010_siteparsesettings_force_parser_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="parsetask",
            name="name",
            field=models.CharField(max_length=100, null=True, verbose_name="Название задачи"),
        ),
    ]
