# Generated by Django 4.2.5 on 2023-09-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser", "0011_parsetask_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parsetask",
            name="monitoring_mode",
            field=models.PositiveSmallIntegerField(
                choices=[("1", "Строгий мониторинг"), ("2", "Гибкий мониторинг"), ("3", "Получение каталогов")],
                default="1",
                verbose_name="Режим мониторинга",
            ),
        ),
    ]
