# Generated by Django 4.2.5 on 2023-09-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser", "0012_alter_parsetask_monitoring_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="parsetask",
            name="is_urls_valid",
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name="parsetask",
            name="monitoring_mode",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Строгий мониторинг"), (2, "Гибкий мониторинг"), (3, "Получение каталогов")],
                default=1,
                verbose_name="Режим мониторинга",
            ),
        ),
        migrations.AlterField(
            model_name="parsetask",
            name="period",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Ежедневно"),
                    (2, "Дважды в месяц"),
                    (3, "Раз в месяц"),
                    (4, "Ежеквартально"),
                    (5, "Единоразово"),
                ],
                default=1,
                verbose_name="Периодичность мониторинга",
            ),
        ),
        migrations.AlterField(
            model_name="parsetask",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Создана"),
                    (2, "В работе"),
                    (3, "Отменена"),
                    (4, "Пауза"),
                    (5, "Остановлена"),
                    (6, "Настройка"),
                ],
                default=1,
                verbose_name="Статус",
            ),
        ),
    ]
