# Generated by Django 4.2.5 on 2023-09-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser", "0013_parsetask_is_urls_valid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parsetask",
            name="is_urls_valid",
        ),
        migrations.AddField(
            model_name="parsetask",
            name="invalid_urls",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
