# Generated by Django 4.2.5 on 2023-09-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser", "0015_alter_parsetask_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="parsetask",
            name="last_run_at",
            field=models.DateTimeField(null=True, verbose_name="Дата последнего запуск"),
        ),
    ]
