# Generated by Django 4.2.5 on 2023-09-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser", "0016_parsetask_last_run_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteparsesettings",
            name="use_selenium",
            field=models.BooleanField(default=False, verbose_name="Использовать Selenium"),
        ),
        migrations.AlterField(
            model_name="parsetask",
            name="last_run_at",
            field=models.DateTimeField(editable=False, null=True, verbose_name="Дата последнего запуск"),
        ),
    ]
