# Generated by Django 4.2.5 on 2023-10-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser", "0018_siteparsesettings_url_before"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteparsesettings",
            name="attribute_price",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Атрибут цены товара"),
        ),
        migrations.AddField(
            model_name="siteparsesettings",
            name="attribute_title",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Атрибут названия товара"),
        ),
    ]
