# Generated by Django 4.2.5 on 2023-11-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser", "0019_siteparsesettings_attribute_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteparsesettings",
            name="match_regex",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Regex страницы задачи"),
        ),
    ]
