# Generated by Django 4.2.2 on 2023-06-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название раздела"
                    ),
                ),
            ],
            options={
                "verbose_name": "Раздел",
                "verbose_name_plural": "Разделы",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название товара"),
                ),
                (
                    "linked_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Связь"
                    ),
                ),
                ("price", models.FloatField(verbose_name="Цена")),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="products.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
