# Generated by Django 4.2.5 on 2024-03-18 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productpricehistory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricehistory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='products.category'),
        ),
        migrations.AddField(
            model_name='productpricehistory',
            name='statusproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='products.statusproduct'),
        ),
    ]
