# Generated by Django 4.2.2 on 2023-06-14 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0001_initial"),
        ("products", "0002_alter_product_options_productpricehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="parser.parsetask",
                verbose_name="Создано задачей",
            ),
        ),
    ]
