# Generated by Django 4.2.5 on 2024-03-18 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productpricehistory_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpricehistory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productpricehistory',
            name='statusproduct',
        ),
    ]
