# Generated by Django 4.2.5 on 2023-09-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_productpricehistory_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="synonyms",
            field=models.TextField(blank=True, verbose_name="Синонимы товара"),
        ),
    ]
