# Generated by Django 4.2.5 on 2024-03-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productpricehistory_statusproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpricehistory',
            name='statusproducts',
        ),
    ]
