# Generated by Django 4.2.5 on 2023-09-06 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0006_productpricehistory_task"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productpricehistory",
            options={"verbose_name": "История цен", "verbose_name_plural": "История цен"},
        ),
        migrations.AddField(
            model_name="product",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор задачи",
            ),
        ),
        migrations.AddField(
            model_name="productpricehistory",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор задачи",
            ),
        ),
    ]
