# Generated by Django 4.2.5 on 2023-09-06 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0007_alter_productpricehistory_options_product_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productpricehistory",
            name="author",
        ),
        migrations.AddField(
            model_name="category",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор задачи",
            ),
        ),
    ]
