# Generated by Django 4.2.5 on 2024-03-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_statusproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusproduct',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название статуса'),
        ),
    ]
