# Generated by Django 4.2.5 on 2023-09-12 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("parser", "0015_alter_parsetask_status"),
        ("products", "0008_remove_productpricehistory_author_category_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpricehistory",
            name="parse_settings",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="parser.siteparsesettings",
                verbose_name="Использованы настройки парсинга",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_created",
                to="parser.parsetask",
                verbose_name="Создано задачей",
            ),
        ),
    ]
