# Generated by Django 4.2.5 on 2024-03-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_statusproduct_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='statusproducts',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.statusproduct'),
        ),
        migrations.AlterField(
            model_name='statusproduct',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название статуса'),
        ),
    ]
