# Generated by Django 4.2.5 on 2024-03-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_statusproducts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricehistory',
            name='competitor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название Конкурента'),
        ),
    ]
